name: Abhishek Kumar, Software Developer
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: "https://mr-kumar-abhishek.github.io/"

paginate_path: "/blog/page:num/"
paginate: 5


plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-mentions
  - jekyll-include-cache
  - jekyll-coffeescript
  - jekyll-seo-tag


